<a href="https://colab.research.google.com/github/marloncalvo/cap4630-spr2020/blob/master/Problem1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Problem 1

Here we are utilizing the well-known `im2loc` algorithm to extract all possible "windows" by imposing kernen into x, into columns of a matrix.

In [0]:
import numpy as np

def im2col(x, kernel):
    kernel_shape = kernel.shape[0]
    rows = []

    for row in range(x.shape[0] -kernel.shape[0]+1):
        for col in range(x.shape[1] -kernel.shape[1]+ 1):
            window = x[row: row + kernel_shape, col: col + kernel_shape]
            rows.append(window.flatten())
                        
    return (np.transpose(np.array(rows)))

x = np.array(
[[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]]
)

k = np.array(
[[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]]
)

a = [1,2,3,4]


Since `im2col` returns all "windows" from `kenel_mat` with stride 1 and valid padding, we can use the following properties.
  
Let, $i$ be our input matrix
$ = \begin{bmatrix}
  1 & 2 & 3 & 4 \\
  5 & 6 & 7 & 8 \\
  9 & 10 & 11 & 12 \\
  13 & 14 & 15 & 16
\end{bmatrix}
$
  
Let, $k$ be our kernel
$ = \begin{bmatrix}
  1 & 2 \\
  3 & 4
\end{bmatrix}
$

Let, $ a = im2loc(i,k) = \begin{bmatrix}
  1 & 2 & ...\\
  2 & 3 & ...\\
  5 & 6 & ...\\
  6 & 7 & ...\\
\end{bmatrix}
$

If we then flatten $k$, we can calculate `conv2d()` on each window.

$$
flatten(k)\times a
$$
$$
conv2d()=
\begin{bmatrix}
  1 & 2 & 3 & 4
\end{bmatrix}
\times
\begin{bmatrix}
  1 & 2 & ...\\
  2 & 3 & ...\\
  5 & 6 & ...\\
  6 & 7 & ...\\
\end{bmatrix}
$$

And that's our answer!

In [0]:
import numpy as np

def conv2d(input_mat, kernel_mat):
  if kernel_mat.shape[0]>input_mat.shape[0] or kernel_mat.shape[1]>input_mat.shape[1]:
    raise Exception('Kernel has larger dimensions than input\n' + str(kernel_mat.shape) + ' '+ str(input_mat.shape))
  (ix, iy) = input_mat.shape
  (kx, ky) = kernel_mat.shape
  v = np.array(im2col(input_mat, kernel_mat))
  _k = kernel_mat.flatten()

  return (_k  @ v).reshape((ix-kx+1,iy-ky+1))

x = np.array(
[[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]]
)

k = np.array(
[[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]]
)

print(conv2d(x,k))

[[4]]


In [0]:
from scipy import signal
import numpy as np

input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])



for i in range(len(input_mat)):
  # uncomment line for student code testing
  print(input_mat[i].shape)
  print(kernel_mat[i].shape)
  output_mat = conv2d(input_mat[i], kernel_mat[i])

  # uncomment lines below (and comment line above) for generating test cases.
  #if input_mat[i].shape[0] < kernel_mat[i].shape[0]:
  #  output_mat = []
  #else:
  #  output_mat = signal.convolve2d(input_mat[i], kernel_mat[i], mode='valid')

  print(output_mat)
  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")


(4, 4)
(2, 2)
[[2 4 2]
 [4 2 4]
 [2 4 2]]
Correct output!

(4, 4)
(2, 2)
[[2 0 0]
 [0 2 0]
 [0 0 2]]
Correct output!

(4, 4)
(2, 2)
[[ 1 -1  0]
 [-1  1 -1]
 [ 0 -1  1]]
Correct output!

(4, 4)
(4, 4)
[[4]]
Correct output!

(2, 2)
(4, 4)


Exception: ignored