<a href="https://colab.research.google.com/github/marloncalvo/cap4630-spr2020/blob/master/Problem2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problem 2 

We are implementing `maxpooling2d()` with numpy, utilizing the well known `im2loc` algorithm, where we can extract all the "windows" of a 2x2 grid imposed on the original data. These are returned as a matrix, where each column contains all the values for "one window". We simply take the max of each column for `maxpooling2d()`.

In [0]:
import numpy as np

def im2col(x, s):
    rows = []
    x_rows = x.shape[0]
    x_cols = x.shape[1]

    x_rows = x_rows if x_rows % 2 == 0 else x_rows - 1
    x_cols = x_cols if x_cols % 2 == 0 else x_cols - 1

    for row in range(0, x_rows, s):
        for col in range(0, x_cols, s):
            window = x[row: row + s, col: col + s]
            rows.append(window.flatten())
                        
    xs = x.shape[0] if x.shape[0] % 2 == 0 else x.shape[0] - 1
    ys = x.shape[1] if x.shape[1] % 2 == 0 else x.shape[1] - 1

    return xs, ys, (np.transpose(np.array(rows)))

Since `im2loc` gives us data in cols, we just need to get max from each column.

In [0]:
def maxpooling2d(input_mat, s):
  if s > input_mat.shape[0] or s > input_mat.shape[1]:
    raise Exception('Pooling box greater than dimensions of input_mat')
    
  x, y, v = im2col(input_mat, s)
  return np.amax(v, axis=0).reshape((int(x/s), int(y/s)))

In [11]:
import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
  # output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)
  print(expected_mat[i])

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")

[[4 2]
 [2 4]]
[[4 2]
 [2 4]]
Correct output!
[[4 2 5]
 [2 4 5]
 [1 3 2]]
[[4, 2, 5], [2, 4, 5], [1, 3, 2]]
Correct output!


In [9]:
maxpooling2d(np.array([[1,2,3],[1,2,3],[1,2,3]]), 2)

array([[2]])